---
- name: Instalar Java 8 e Python 3
  hosts: all
  become: yes  # executa com sudo
  tasks:

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Instalar Java 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Instalar Python 3 e pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Verificar vers√µes instaladas
      shell: |
        java -version
        python3 --version
      register: version_output

    - debug:
        var: version_output.stdout_lines
